server:
  port: 8080
  tomcat:
   threads:
    max: 500
   connection-timeout: 5s
spring:
 thymeleaf:
    cache: false
 datasource:
  url: jdbc:mariadb://localhost:3306/pessoal?createDatabaseIfNotExist=true
  username: root
  password: root
  driver-class-name: org.mariadb.jdbc.Driver
  hikari:
    connection-timeout: 300000
    maximum-pool-size: 500
    max-lifetime: 180000
    minimum-idle: 200
    validation-timeout: 3000
    idle-timeout: 10000
 jpa:
   open-in-view: false
   database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
   generate-ddl: true
   properties:
     hibernate:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      ddl-auto: none
   show-sql: true
logging:
  file: 
   name: "c:/logs/pessoal/pessoal.log"
  level:
    org:
      hibernate:
        type: info
    jdbc: info
    root: info